# Site settings
title: BRIDGE Documentation
description: Documentation for BRIDGE - Block Rewiring from Inference-Derived Graph Ensembles
baseurl: "/BRIDGE" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Aux links for the upper right navigation
aux_links:
  "BRIDGE on GitHub":
    - "https://github.com/jr419/BRIDGE"

# Enable search
search_enabled: true

# Enable copy code button
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2025 Jonathan Rubin. Distributed under the <a href=\"https://github.com/jr419/BRIDGE/blob/main/LICENSE\">MIT License.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
